language: ruby
rvm:
  - 2.1.3
env:
  global:
    - AWS_S3_REGION= <%= ENV["AWS_S3_REGION"] %>
    - AWS_S3_BUCKET= <%= ENV["AWS_S3_BUCKET"] %>
    - AWS_ACCESS_KEY_ID= <%= ENV["AWS_ACCESS_KEY_ID"] %>
    - AWS_SECRET_ACCESS_KEY= <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
before_script:
  - cp config/database.yml.travis config/database.yml
  - "RAILS_ENV=test bundle exec rake db:create db:migrate"
script: bundle exec rspec spec
