language: ruby
env:
  - DB=postgres
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - "RAILS_ENV=test bundle exec rake db:create db:migrate"
script: bundle exec rspec spec
